### ISSUE TITLE
READme screenshot breaks in Gatsby Cloud clone

### ISSUE THREAD

**Issue by shannonbux** [cosmicjs/gatsby-blog-cosmicjs#7]
Problem

Very small issue, but when I used this starter via Gatsby Cloud, the screenshot in the READme of my copy of the starter seems broken.

https://github.com/shannonbux/cosmicjs-test-1-24

**Comment by tonyspiro** [comment]
Thanks @shannonbux This is strange.

**Comment by tonyspiro** [comment]
Thank you @shannonbux switched the image from reference in the repo to a URL and that seems to have fixed it. Still not sure what the issue was with copying the image over from the API. Forking from the GitHub UI doesn't cause this error 🤷‍♂

**Comment by shannonbux** [comment]
Thank you!
